import type { SampleCharacter } from "@forge/core";
import { t } from "./helpers";

/** Level 3 pregens, one per classic role, so a new player can sit down and play. */
export const samples: SampleCharacter[] = [
  {
    id: "sample:fighter",
    name: t("Bren Ironoath", "布伦·铁誓"),
    text: t("Human soldier and Champion: chain mail, a greatsword, and more critical hits than anyone else.", "人类老兵，勇士范型。锁子甲配巨剑，暴击比谁都多，站在最前面替大家挨刀。"),
    level: 3,
    classId: "class:fighter",
    speciesId: "species:human",
    backgroundId: "background:soldier",
    abilities: { str: 15, dex: 13, con: 14, int: 8, wis: 12, cha: 10 },
    choices: {
      "background:soldier/ability": ["str:2", "con:1"],
      "class:fighter/skills": ["athletics", "perception"],
      "class:fighter@1/fighting-style": ["feat:defense"],
      "class:fighter@1/weapon-mastery": ["item:longsword", "item:javelin", "item:greatsword"],
      "class:fighter@3/subclass": ["subclass:champion"],
      "species:human/skillful": ["insight"],
      "species:human/versatile": ["feat:alert"],
    },
  },
  {
    id: "sample:rogue",
    name: t("Mira Lightfoot", "米拉·轻步"),
    text: t("Halfling criminal and Thief: Sneak Attack, Cunning Action, and a hand in every pocket.", "半身人罪犯，盗贼范型。偷袭、灵巧动作，手总在别人的口袋里。"),
    level: 3,
    classId: "class:rogue",
    speciesId: "species:halfling",
    backgroundId: "background:criminal",
    abilities: { str: 8, dex: 15, con: 14, int: 13, wis: 12, cha: 10 },
    choices: {
      "background:criminal/ability": ["dex:2", "int:1"],
      "class:rogue/skills": ["acrobatics", "perception", "deception", "investigation"],
      "class:rogue@1/expertise": ["stealth", "perception"],
      "class:rogue@1/weapon-mastery": ["item:dagger", "item:shortbow"],
      "class:rogue@3/subclass": ["subclass:thief"],
    },
  },
  {
    id: "sample:cleric",
    name: t("Dagna Hearthstone", "达格娜·炉石"),
    text: t("Dwarf acolyte of the Life Domain: heals the party, blesses the fight, wears heavy armor.", "矮人侍僧，生命领域。治疗队友、祝福战斗，还穿得动重甲。"),
    level: 3,
    classId: "class:cleric",
    speciesId: "species:dwarf",
    backgroundId: "background:acolyte",
    abilities: { str: 13, dex: 10, con: 14, int: 8, wis: 15, cha: 12 },
    choices: {
      "background:acolyte/ability": ["wis:2", "cha:1"],
      "background:acolyte/feat:magic-initiate-cleric/ability": ["wis"],
      "class:cleric/skills": ["medicine", "persuasion"],
      "class:cleric@1/cantrips": ["spell:sacred-flame", "spell:guidance", "spell:thaumaturgy"],
      "class:cleric@1/divine-order": ["protector"],
      "class:cleric@3/subclass": ["subclass:life-domain"],
    },
    prepared: { "class:cleric": ["spell:guiding-bolt", "spell:healing-word", "spell:shield-of-faith", "spell:sanctuary", "spell:spiritual-weapon", "spell:command"] },
  },
  {
    id: "sample:wizard",
    name: t("Elaria Starwhisper", "艾拉瑞·星语"),
    text: t("High elf sage and Evoker: Magic Missile, Shield, and a Fireball-shaped future.", "高等精灵学者，塑能学派。魔法飞弹、护盾术，未来属于火球。"),
    level: 3,
    classId: "class:wizard",
    speciesId: "species:elf",
    backgroundId: "background:sage",
    abilities: { str: 8, dex: 14, con: 13, int: 15, wis: 12, cha: 10 },
    choices: {
      "species:elf/lineage": ["high-elf"],
      "species:elf/spell-ability": ["int"],
      "species:elf/keen-senses": ["perception"],
      "background:sage/ability": ["int:2", "con:1"],
      "background:sage/feat:magic-initiate-wizard/ability": ["int"],
      "class:wizard/skills": ["investigation", "insight"],
      "class:wizard@1/cantrips": ["spell:fire-bolt", "spell:mage-hand", "spell:minor-illusion"],
      "class:wizard@1/spellbook": ["spell:magic-missile", "spell:shield", "spell:mage-armor", "spell:sleep", "spell:burning-hands", "spell:detect-magic"],
      "class:wizard@2/spellbook": ["spell:thunderwave", "spell:find-familiar"],
      "class:wizard@3/subclass": ["subclass:evoker"],
      "class:wizard@3/spellbook": ["spell:misty-step", "spell:scorching-ray"],
    },
    prepared: { "class:wizard": ["spell:magic-missile", "spell:shield", "spell:mage-armor", "spell:sleep", "spell:misty-step", "spell:scorching-ray"] },
  },
];
