import type { RulePack } from "../src";

/** Minimal pack exercising every engine feature, independent of real content. */
export const fixturePack: RulePack = {
  id: "fixture",
  version: "1.0.0",
  system: "dnd5e-2024",
  name: "Fixture",
  globalGrants: [
    { type: "action", action: { id: "dodge", name: { en: "Dodge", zh: "闪避" }, activation: "action" } },
  ],
  entities: [
    {
      id: "species:dwarf",
      type: "species",
      name: { en: "Dwarf", zh: "矮人" },
      size: "Medium",
      speed: 30,
      grants: [
        { type: "modifier", target: "sense.darkvision", op: "atLeast", value: 120 },
        { type: "modifier", target: "hp.max", value: "@level", label: { en: "Dwarven Toughness", zh: "矮人韧性" } },
        { type: "tag", tag: "resist:poison" },
      ],
    },
    { id: "species:human", type: "species", name: "Human", size: "Medium", speed: 30, grants: [{ type: "grant", entity: "feat:alert" }] },
    {
      id: "background:soldier",
      type: "background",
      name: "Soldier",
      grants: [
        { type: "choice", id: "ability", name: "Ability Scores", count: 1, from: { kind: "ability", abilities: ["str", "dex", "con"], patterns: [[2, 1], [1, 1, 1]] } },
        { type: "proficiency", kind: "skill", key: "athletics" },
        { type: "proficiency", kind: "skill", key: "intimidation" },
        { type: "grant", entity: "feat:alert" },
      ],
    },
    {
      id: "feat:alert",
      type: "feat",
      category: "origin",
      name: { en: "Alert", zh: "警觉" },
      grants: [{ type: "modifier", target: "initiative", value: "@prof" }],
    },
    {
      id: "feat:archery",
      type: "feat",
      category: "fighting-style",
      name: "Archery",
      tags: ["fighting-style"],
      grants: [{ type: "modifier", target: "attack.ranged", value: 2 }],
    },
    {
      id: "feat:defense",
      type: "feat",
      category: "fighting-style",
      name: "Defense",
      tags: ["fighting-style"],
      grants: [{ type: "modifier", target: "ac", value: 1, when: "@equipped.armor" }],
    },
    {
      id: "class:fighter",
      type: "class",
      name: { en: "Fighter", zh: "战士" },
      hitDie: 10,
      primaryAbility: ["str", "dex"],
      subclassLevel: 3,
      starting: [
        { type: "proficiency", kind: "save", key: "str" },
        { type: "proficiency", kind: "save", key: "con" },
        { type: "choice", id: "skills", name: "Skills", count: 2, from: { kind: "proficiency", profKind: "skill", keys: ["acrobatics", "athletics", "perception", "survival"] } },
        { type: "item", item: "item:chain-mail", equipped: true },
        { type: "item", item: "item:longsword", equipped: true },
      ],
      multiclass: [{ type: "proficiency", kind: "weapon", key: "martial" }],
      grants: [
        { type: "proficiency", kind: "armor", key: "heavy" },
        { type: "proficiency", kind: "weapon", key: "simple" },
        { type: "proficiency", kind: "weapon", key: "martial" },
      ],
      levels: {
        "1": [
          { type: "choice", id: "fighting-style", name: "Fighting Style", count: 1, from: { kind: "entity", entityType: "feat", tags: ["fighting-style"] } },
          {
            type: "feature",
            id: "second-wind",
            name: "Second Wind",
            grants: [
              { type: "resource", id: "second-wind", name: "Second Wind", max: "table(@class.fighter.level, 2,2,2,3,3,3,3,3,3,4)", recovery: [{ on: "short", amount: 1 }, { on: "long", amount: "all" }] },
              { type: "action", action: { id: "second-wind", name: "Second Wind", activation: "bonus", cost: [{ resource: "second-wind" }], heal: { dice: "1d10 + @class.fighter.level" } } },
            ],
          },
        ],
        "2": [{ type: "feature", id: "action-surge", name: "Action Surge", grants: [{ type: "resource", id: "action-surge", name: "Action Surge", max: 1, recovery: [{ on: "short", amount: "all" }] }] }],
        "3": [{ type: "choice", id: "subclass", name: "Subclass", count: 1, from: { kind: "entity", entityType: "subclass", tags: ["fighter"] } }],
      },
    },
    {
      id: "subclass:champion",
      type: "subclass",
      classId: "class:fighter",
      name: "Champion",
      tags: ["fighter"],
      levels: { "3": [{ type: "feature", id: "improved-critical", name: "Improved Critical", tags: ["crit-19"] }] },
    },
    {
      id: "class:wizard",
      type: "class",
      name: { en: "Wizard", zh: "法师" },
      hitDie: 6,
      primaryAbility: ["int"],
      subclassLevel: 3,
      starting: [
        { type: "proficiency", kind: "save", key: "int" },
        { type: "proficiency", kind: "save", key: "wis" },
      ],
      multiclass: [],
      levels: {
        "1": [
          { type: "spellcasting", classId: "class:wizard", ability: "int", progression: "full", list: "wizard", mode: "spellbook", cantrips: "table(@class.wizard.level, 3,3,3,4)", prepared: "table(@class.wizard.level, 4,5,6,7,9)" },
          { type: "choice", id: "cantrips", name: "Cantrips", count: 3, from: { kind: "entity", entityType: "spell", tags: ["wizard"], maxLevel: 0 } },
          { type: "choice", id: "spellbook", name: "Spellbook", count: 6, from: { kind: "entity", entityType: "spell", tags: ["wizard"], minLevel: 1, maxLevel: "@spell.wizard.max-level" } },
          { type: "feature", id: "arcane-recovery", name: "Arcane Recovery", grants: [{ type: "resource", id: "arcane-recovery", name: "Arcane Recovery", max: 1, recovery: [{ on: "long", amount: "all" }] }] },
        ],
        "2": [{ type: "choice", id: "spellbook", name: "Spellbook", count: 2, from: { kind: "entity", entityType: "spell", tags: ["wizard"], minLevel: 1, maxLevel: 1 } }],
        "3": [{ type: "choice", id: "spellbook", name: "Spellbook", count: 2, from: { kind: "entity", entityType: "spell", tags: ["wizard"], minLevel: 1, maxLevel: 2 } }],
      },
    },
    {
      id: "spell:fire-bolt",
      type: "spell",
      name: { en: "Fire Bolt", zh: "火焰箭" },
      tags: ["wizard"],
      level: 0,
      school: "evocation",
      castingTime: "1 action",
      activation: "action",
      range: "120 ft",
      components: "V, S",
      duration: "Instantaneous",
      cantripScaling: true,
      action: { attack: { bonus: 0, kind: "spell" }, damage: [{ dice: "1d10", type: "fire" }] },
    },
    { id: "spell:light", type: "spell", name: "Light", tags: ["wizard"], level: 0, school: "evocation", castingTime: "1 action", activation: "action", range: "Touch", components: "V, M", duration: "1 hour" },
    { id: "spell:mage-hand", type: "spell", name: "Mage Hand", tags: ["wizard"], level: 0, school: "conjuration", castingTime: "1 action", activation: "action", range: "30 ft", components: "V, S", duration: "1 minute" },
    {
      id: "spell:magic-missile",
      type: "spell",
      name: "Magic Missile",
      tags: ["wizard"],
      level: 1,
      school: "evocation",
      castingTime: "1 action",
      activation: "action",
      range: "120 ft",
      components: "V, S",
      duration: "Instantaneous",
      action: { damage: [{ dice: "3d4+3", type: "force" }] },
      upcast: { damage: "1d4+1" },
    },
    { id: "spell:shield", type: "spell", name: "Shield", tags: ["wizard"], level: 1, school: "abjuration", castingTime: "Reaction", activation: "reaction", range: "Self", components: "V, S", duration: "1 round" },
    { id: "spell:sleep", type: "spell", name: "Sleep", tags: ["wizard"], level: 1, school: "enchantment", castingTime: "1 action", activation: "action", range: "60 ft", components: "V, S, M", duration: "1 minute", concentration: true, action: { save: { ability: "wis", dc: 0 } } },
    { id: "spell:detect-magic", type: "spell", name: "Detect Magic", tags: ["wizard"], level: 1, school: "divination", castingTime: "1 action", activation: "action", range: "Self", components: "V, S", duration: "10 minutes", concentration: true, ritual: true },
    { id: "spell:mage-armor", type: "spell", name: "Mage Armor", tags: ["wizard"], level: 1, school: "abjuration", castingTime: "1 action", activation: "action", range: "Touch", components: "V, S, M", duration: "8 hours" },
    { id: "spell:burning-hands", type: "spell", name: "Burning Hands", tags: ["wizard"], level: 1, school: "evocation", castingTime: "1 action", activation: "action", range: "Self", components: "V, S", duration: "Instantaneous", action: { save: { ability: "dex", dc: 0, onSave: "half" }, damage: [{ dice: "3d6", type: "fire" }] } },
    { id: "spell:misty-step", type: "spell", name: "Misty Step", tags: ["wizard"], level: 2, school: "conjuration", castingTime: "Bonus action", activation: "bonus", range: "Self", components: "V", duration: "Instantaneous" },
    { id: "item:chain-mail", type: "item", itemType: "armor", name: "Chain Mail", armor: { category: "heavy", ac: 16, strength: 13 } },
    { id: "item:leather", type: "item", itemType: "armor", name: "Leather Armor", armor: { category: "light", ac: 11 } },
    { id: "item:shield", type: "item", itemType: "armor", name: "Shield", armor: { category: "shield", ac: 2 } },
    { id: "item:longsword", type: "item", itemType: "weapon", name: "Longsword", weapon: { category: "martial", kind: "melee", damage: "1d8", damageType: "slashing", properties: ["versatile"], versatile: "1d10", mastery: "sap" } },
    { id: "item:longbow", type: "item", itemType: "weapon", name: "Longbow", weapon: { category: "martial", kind: "ranged", damage: "1d8", damageType: "piercing", properties: ["ammunition", "heavy", "two-handed"], range: "150/600", mastery: "slow" } },
    {
      id: "effect:bless",
      type: "effect",
      name: "Bless",
      grants: [{ type: "tag", tag: "blessed" }],
    },
    {
      id: "effect:haste",
      type: "effect",
      name: "Haste",
      grants: [{ type: "modifier", target: "ac", value: 2 }],
    },
  ],
};
